services:
  redis:
    image: redis:7
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - osmodoc-net

  osmodoc-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-api
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:5000
    environment:
      - REDIS_URL=${REDIS_HOST}:${REDIS_PORT}
    depends_on:
      - redis
    volumes:
      - ./Temp:/app/wwwroot/Temp
    networks:
      - osmodoc-net

networks:
  osmodoc-net:
    driver: bridge